# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'SearchItems' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchItems

pod 'Alamofire', '~> 5.4'
pod 'Kingfisher', '~> 7.0'
pod 'RxSwift', '~> 4.0'
pod 'RxCocoa', '~> 4.0'

  target 'SearchItemsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchItemsUITests' do
    # Pods for testing
  end

end
